routes:
  /.well-known/site.standard.publication/:
    template: standard-site-publication
    content_type: text/plain

  /updates/rss/:
    template: updates-rss
    content_type: text/xml

  /updates/feed.json/:
    template: updates-json
    content_type: application/feed+json

  /urbanism/:
    controller: channel
    template: custom-urbanism
    filter: 'tag:[urbanism,housing,transportation,public-finance]'
    data: tag.urbanism

  /field-notes/:
    controller: channel
    template: custom-field-notes
    filter: 'tag:[field-notes,urbanism,housing,transportation,public-finance]'
    data: tag.field-notes

  /gallery/:
    controller: channel
    template: custom-gallery
    filter: 'tag:[gallery,hash-gallery,photography,hash-photography]'
    data: tag.gallery

  /posts/:
    controller: channel
    template: custom-posts
    filter: 'tag:-[status,note,notes,afterword,listening,hash-crucialtracks,check-ins]'

  /check-ins/:
    controller: channel
    template: custom-check-ins
    filter: 'tag:check-ins'

collections:
  /notes/:
    permalink: /notes/{slug}/
    template: custom-notes
    filter: 'tag:[status,note,notes,afterword]'
    data: tag.status

  /:
    permalink: /{slug}/
    template: index
    filter: 'tag:-[status,note,notes,afterword,listening,hash-crucialtracks,check-ins]'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
